# Generated by Django 4.1.1 on 2022-12-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_slug'),
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_bid',
            name='products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
