# Generated by Django 4.1.1 on 2022-12-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_bid_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto_bid',
            name='is_auto_bidding_active',
        ),
    ]
